<?php

namespace Ach\PoManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BpoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BpoRepository extends EntityRepository
{

	const SELECT_ALL = 'SELECT b FROM AchPoManagerBundle:Bpo b ';
	const JOIN_REV_PRODUCT = 'JOIN b.revision r JOIN r.product p ';
	const DATE_FILTER_ORDER = 'h.shippingDate >= :earliest AND h.shippingDate <= :latest ORDER BY h.shippingDate DESC';
	
	private function setParameterWithFilter($paramKey, $paramValue, $query, $filterDate, $exact = false)
	{
		if($exact)
		{
			$query->setParameter($paramKey, $paramValue);
		}
		else
		{
			$query->setParameter($paramKey, '%' . $paramValue . '%');
		}
		
		$query->setParameter('earliest', $filterDate['earliest']);
		$query->setParameter('latest', $filterDate['latest']);
	}
	
	public function findByBpoNum($bpoNum, $exact)
	{
		echo 'oudin';
		$query = $this->_em->createQuery(self::SELECT_ALL . ' WHERE b.num like :num');
		
		if($exact)
		{
			$query->setParameter('num', $bpoNum);
		}
		else
		{
			$query->setParameter('num', '%' . $bpoNum . '%');
		}
		
		return $query->getResult();
	}
	
	public function findByPn($pn, $exact)
	{
		
		$query = $this->_em->createQuery(self::SELECT_ALL . self::JOIN_REV_PRODUCT . 'WHERE p.pn like :pn');
		
		if($exact)
		{
			$query->setParameter('pn', $pn);
		}
		else
		{
			$query->setParameter('pn', '%' . $pn . '%');
		}
		
		return $query->getResult();
		
	}
	
	public function findByCustPn($custPn, $exact)
	{
		
		$query = $this->_em->createQuery(self::SELECT_ALL . self::JOIN_REV_PRODUCT . 'WHERE p.custPn like :custPn');
		
		if($exact)
		{
			$query->setParameter('custPn', $custPn);
		}
		else
		{
			$query->setParameter('custPn', '%' . $custPn . '%');
		}
		
		return $query->getResult();
		
	}
	
	public function findByDescription($desc)
	{
		$query = $this->_em->createQuery(self::SELECT_ALL . self::JOIN_REV_PRODUCT . 'WHERE p.description like :desc');
		
		$query->setParameter('desc', '%' . $desc . '%');
		
		return $query->getResult();
	}
	
}
