<?php

namespace Ach\PoManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findPn($pn)
    {
        $query = $this->_em->createQuery('SELECT p FROM AchPoManagerBundle:Product p WHERE p.pn like :pn');
	$query->setParameter('pn', '%' . $pn . '%');
	return $query->getResult();
    }

    public function findPnActive($pn)
    {
        $query = $this->_em->createQuery('SELECT p FROM AchPoManagerBundle:Product p WHERE p.pn like :pn AND p.active=1');
	$query->setParameter('pn', '%' . $pn . '%');
	return $query->getResult();
    }


    public function findCustPn($pn)
    {
        $query = $this->_em->createQuery('SELECT p FROM AchPoManagerBundle:Product p WHERE p.custPn like :pn');
	$query->setParameter('pn', '%' . $pn . '%');
	return $query->getResult();
    }

    public function findCustPnActive($pn)
    {
        $query = $this->_em->createQuery('SELECT p FROM AchPoManagerBundle:Product p WHERE p.custPn like :pn AND p.active=1');
	$query->setParameter('pn', '%' . $pn . '%');
	return $query->getResult();
    }


    public function findDescription($desc)
    {
        $query = $this->_em->createQuery('SELECT p FROM AchPoManagerBundle:Product p WHERE p.description like :desc');
	$query->setParameter('desc', '%' . $desc . '%');
	return $query->getResult();
    }

    public function findMasterProducts()
    {
        $query = $this->_em->createQuery('SELECT p FROM AchPoManagerBundle:Product p WHERE SIZE(p.spareParts) > 0');
        return $query->getResult();
    }

}
