<?php

namespace Ach\PoManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SerialNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerialNumberRepository extends EntityRepository
{
    public function findBySerialNumber($sn)
    {
        $query = $this->_em->createQuery('SELECT s FROM AchPoManagerBundle:SerialNumber s WHERE s.serialNumber like :sn');
        $query->setParameter('sn', '%' . $sn . '%');
        return $query->getResult();
    }

    public function findByMacAddress($mac)
    {
        $query = $this->_em->createQuery('SELECT s FROM AchPoManagerBundle:SerialNumber s WHERE s.macAddress like :mac');
        $query->setParameter('mac', '%' . $mac . '%');
        return $query->getResult();
    }

}

