imports:
    - { resource: '../../../../../app/config/parameters.yml' }

parameters:
#    ach_po_manager.example.class: Ach\PoManagerBundle\Example
    # po_files_path:		%po_files_path%
    # bpo_files_path:		%bpo_files_path%
    # invoice_files_path:		%invoice_files_path%

#services:
#    ach_po_manager.example:
#        class: %ach_po_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    ach_po_manager.variable_substitution:
        class: Ach\PoManagerBundle\VariableSubstitute\AchVariableSubstitute
    ach_po_manager.send_notification:
        class: Ach\PoManagerBundle\SendNotification\AchSendNotification
        arguments: [@mailer, @swiftmailer.transport.real, @router, @templating, @phpexcel ,%po_files_path%, %bpo_files_path%, %invoice_files_path%, %rma_files_path%, %from_emails%]
#        scope: request
    ach_po_manager.generate_xls_response:
        class: Ach\PoManagerBundle\GenerateXlsResponse\AchGenerateXlsResponse
        arguments: [@phpexcel]
    ach_po_manager.notification_creator:
        class: Ach\PoManagerBundle\NotificationCreator\AchNotificationCreator
        arguments: [@doctrine.orm.entity_manager]
    ach_po_manager.connect_prod_database:
        class: Ach\PoManagerBundle\ConnectProdDatabase\AchConnectProdDatabase
        arguments: [%external_sql%]
    ach_po_manager.sync_prod_database:
        class: Ach\PoManagerBundle\SyncProdDatabase\AchSyncProdDatabase
        arguments: [@doctrine.orm.entity_manager, @ach_po_manager.connect_prod_database, %lot%]
    ach_po_manager.upload_elifesheet:
        class: Ach\PoManagerBundle\UploadElifesheet\AchUploadElifesheet
        arguments: [@doctrine.orm.entity_manager, @ach_po_manager.connect_prod_database]

